### ISSUE TITLE
对战答题报错Wrapped com.stardust.autojs.runtime.exception.ScriptException

### ISSUE THREAD

**Issue by HinSIU** [dundunnp/hamibot-auto_xuexiqiangguo#155]
11:11:49.468/E: Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1. (<init>#30)
Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
    at <init>:30:0
    at do_it (61f4ae8e51b2481a8a06da90.js:339:0)
    at 61f4ae8e51b2481a8a06da90.js:396:0

**Comment by oyjs1989** [comment]
the same problem,
