### ISSUE TITLE
Wrapped com.stardust.autojs.runtime.exception.ScriptException

### ISSUE THREAD

**Issue by xxxxxy211** [dundunnp/hamibot-auto_xuexiqiangguo#29]
报错日志如下：
11:41:36.115/E: Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1. (<init>#30)
Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
    at <init>:30:0
    at do_periodic_answer (61ab875a04cdd891c8479776.js:575:0)
    at 61ab875a04cdd891c8479776.js:622:0

**Comment by iChoix** [comment]
![image](https://user-images.githubusercontent.com/6520601/144778668-55b520fe-ad44-47da-9a8e-7098765e5718.png)
报错如图。请各位指点迷津。感谢
