### ISSUE TITLE
主脚本5.0和副脚本2.1双人答题bug

### ISSUE THREAD

**Issue by gitgithubhub1dot** [dundunnp/hamibot-auto_xuexiqiangguo#31]
> 感谢大佬及时更新
今天在测试的时候又出现新的bug
> 软件已更新到最新，脚本为5.0和2.1

> 在运行主脚本四人答题结束后自动进入双人答题界面，然后bug并结束运行，bug如下。重新运行主脚本依旧提示如下：

12:33:12.530/：开始运行
T61ab5eef67479173a3cab7c1.js]
12:33:32.849/E: TypeError:
Cannot call method "click" of null
(61ab5eef67479173a3cab7c1.js#744）
TypeError: Cannot call method "click" of null
at 61 ab5eef67479173a3cab7c1.js:744:0
12:33.32.851/V:
T61ab5e167479173a3cab701.js1运行结
束，用时20.321000秒

> 接着尝试副脚本，四人答题结束后，跳转至双人页面后bug，并自动结束脚本运行，重新运行提示相同bug，内容如下

12:32:36.116/D4.苏州古典园林是中国
12:32:40.657/D:5.新中国成立后，我国为发
挥各族人民当家作主的积极性，发展平等、区
结、互助的社会主义民族关系，巩固国家的统
，促进全国社会主义建设事业的发展而实行
的基本政治制度是
12:32:55.090/E: TypeError:
Cannot call method "click" of null
(61ab5f2667479173a3cab7d1.js#246)
TypeError: Cannot call method "click" of null
at 61ab5f2667479173a3cab7d1.js:246:0
12:32.55.093/V:
「61ab512667479173a3cab7d1.js」 运行结
束，用时99.1326000秒

**Comment by gitgithubhub1dot** [comment]
关于distance的配置我已经测量并配置好了的，排除了hamibot上脚本设置问题
