### ISSUE TITLE
下载题库报错

### ISSUE THREAD

**Issue by laiyicizai** [dundunnp/hamibot-auto_xuexiqiangguo#314]
下载题库报错

**Comment by hanajoruno** [comment]
脚本里第一个题库挂了, 删除131-134行和137行

**Comment by geniusNFIL** [comment]
giehub牛逼！项目牛逼！我也是遇到这个问题：
17:16:50.659/E: SyntaxError: JSON.parse (file:///android_asset/modules/__json2__.js#505)
SyntaxError: JSON.parse
    at file:///android_asset/modules/__json2__.js:505:0
    at 625cc79c9135d3de7c0c1502.js:142:0

然后我看到议题有人提了这个问题，原来是挂了，我现在去试试，如果没问题，就不回复了，如果有问题，就回复一下，问题情况，真心强势！给大佬点赞！必须点赞！
