### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yhuaqiang** [dundunnp/hamibot-auto_xuexiqiangguo#34]
16:19:21.056/E: Wrapped java.lang.IllegalArgumentException: Path bounds must not be negative (file:///android_asset/modules/__automator__.js#17)
Wrapped java.lang.IllegalArgumentException: Path bounds must not be negative
    at file:///android_asset/modules/__automator__.js:17:0
    at 61ac73d304cdd891c847d2f9.js:164:0

**Comment by PlayWithSanLei** [comment]
我重启了一下软件暂时好了,还没报错,观察一下
