### ISSUE TITLE
看看这是什么问题？

### ISSUE THREAD

**Issue by 2502452579** [dundunnp/hamibot-auto_xuexiqiangguo#78]
感觉配置都没问题，然后报这个错

00:17:32.645/E: Cannot convert NaN to java.lang.Integer (file:///android_asset/modules/__images__.js#521)
Cannot convert NaN to java.lang.Integer
    at buildRegion (file:///android_asset/modules/__images__.js:521:0)
    at file:///android_asset/modules/__images__.js:348:0
    at 61b766f1e144b510ed74757a.js:203:0

**Comment by chaotianjiao** [comment]
我也是这个问题
